export const MILLISECONDS_IN_A_SECOND = 1000;
export const SECONDS_IN_A_MINUTE = 60;
export const MILLISECONDS_IN_A_MINUTE =
	MILLISECONDS_IN_A_SECOND * SECONDS_IN_A_MINUTE;

export const DEFAULT_MAX_ATTEMPTS = 5;
export const DEFAULT_CONCURRENCY = 5;
export const DEFAULT_POLL_INTERVAL_MS = MILLISECONDS_IN_A_SECOND;
export const DEFAULT_LEASE_MS = 30 * MILLISECONDS_IN_A_SECOND;

export const DEFAULT_BACKOFF_BASE_MS = MILLISECONDS_IN_A_SECOND;
export const DEFAULT_BACKOFF_FACTOR = 2;
export const DEFAULT_BACKOFF_MAX_MS = 5 * MILLISECONDS_IN_A_MINUTE;
